# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 791, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.inputs = QtWidgets.QWidget()
        self.inputs.setObjectName("inputs")
        self.tableWidget = QtWidgets.QTableWidget(self.inputs)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 591, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.inputs)
        self.pushButton.setGeometry(QtCore.QRect(610, 10, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.inputs)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 591, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.inputs)
        self.label.setGeometry(QtCore.QRect(10, 69, 591, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.inputs, "")
        self.result = QtWidgets.QWidget()
        self.result.setObjectName("result")
        self.tabWidget.addTab(self.result, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Select .CSV File"))
        self.label.setText(_translate("MainWindow", "Enter Target Weights"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.inputs), _translate("MainWindow", "Inputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.result), _translate("MainWindow", "Result"))
